export const validtableColumnConfig = [
  {
    type: 'index',
    label: '序号',
    with: '50px',
    sortable: false,
    fixed: 'left',
  },
  {
    label: '授信编号',
    prop: 'limitNo',
    'show-overflow-tooltip': true,
    'min-width': '180px',
    fixed: 'left',
    isNeedTemplate: true,
  },
  {
    label: '企业名称',
    prop: 'companyName',
    'show-overflow-tooltip': true,
    'min-width': '140px',
  },
  {
    label: '授信企业类型',
    prop: 'enterpriseType',
    'show-overflow-tooltip': true,
    'min-width': '120px',
    isFormatDict: true,
  },
  {
    label: '额度类型',
    prop: 'creditType',
    'show-overflow-tooltip': true,
    'min-width': '120px',
    isFormatDict: true,
  },
  {
    label: '授信金额（元）',
    prop: 'creditAmount',
    'show-overflow-tooltip': true,
    'min-width': '140px',
    isFormatMoney: true,
    align: 'right',
  },
  {
    label: '反向保理额度（元）',
    prop: 'reverseCreditAmount',
    'show-overflow-tooltip': true,
    'min-width': '160px',
    isFormatMoney: true,
    align: 'right',
  },
  {
    label: '剩余反向保理额度（元）',
    prop: 'reverseAvailableBalance',
    'show-overflow-tooltip': true,
    'min-width': '180px',
    isFormatMoney: true,
    align: 'right',
  },
  {
    label: '剩余可用额度（元）',
    prop: 'availableBalance',
    'show-overflow-tooltip': true,
    'min-width': '160px',
    isFormatMoney: true,
    align: 'right',
  },
  {
    label: '预占用额度（元）',
    prop: 'prepareUsedAmount',
    'show-overflow-tooltip': true,
    'min-width': '140px',
    isFormatMoney: true,
    align: 'right',
  },
  {
    label: '创建日期',
    prop: 'createTime',
    'show-overflow-tooltip': true,
    isNeedTemplate: true,
    'min-width': '120px',
  },
  {
    label: '授信到期日',
    prop: 'limitEndDate',
    'show-overflow-tooltip': true,
    'min-width': '120px',
  },
  {
    label: '额度状态',
    prop: 'limitStatus',
    'show-overflow-tooltip': true,
    'min-width': '120px',
    isFormatDict: true,
  },
  {
    label: '操作',
    prop: 'action',
    isNeedTemplate: true,
    'show-overflow-tooltip': true,
    sortable: false,
    fixed: 'right',
  },
];

export const invalidtableColumnConfig = [
  {
    type: 'index',
    label: '序号',
    with: '50px',
    sortable: false,
    fixed: 'left',
  },
  {
    label: '授信编号',
    prop: 'limitNo',
    'show-overflow-tooltip': true,
    'min-width': '180px',
    fixed: 'left',
    isNeedTemplate: true,
  },
  {
    label: '企业名称',
    prop: 'companyName',
    'show-overflow-tooltip': true,
    'min-width': '140px',
  },
  {
    label: '授信企业类型',
    prop: 'enterpriseType',
    'show-overflow-tooltip': true,
    'min-width': '120px',
    isFormatDict: true,
  },
  {
    label: '额度类型',
    prop: 'creditType',
    'show-overflow-tooltip': true,
    'min-width': '120px',
    isFormatDict: true,
  },
  {
    label: '授信金额（元）',
    prop: 'creditAmount',
    'show-overflow-tooltip': true,
    'min-width': '140px',
    isFormatMoney: true,
    align: 'right',
  },
  {
    label: '反向保理额度（元）',
    prop: 'reverseCreditAmount',
    'show-overflow-tooltip': true,
    'min-width': '160px',
    isFormatMoney: true,
    align: 'right',
  },
  {
    label: '创建日期',
    prop: 'createTime',
    'show-overflow-tooltip': true,
    isNeedTemplate: true,
    'min-width': '120px',
  },
  {
    label: '授信到期日',
    prop: 'endDate',
    'show-overflow-tooltip': true,
    'min-width': '120px',
  },
  {
    label: '授信期限（天）',
    prop: 'creditPeriod',
    'show-overflow-tooltip': true,
    'min-width': '140px',
  },
  {
    label: '操作',
    prop: 'action',
    isNeedTemplate: true,
    'show-overflow-tooltip': true,
    sortable: false,
    fixed: 'right',
  },
];

export const limitDetailTableColumnConfig = [
  {
    type: 'index',
    label: '序号',
    with: '50px',
    sortable: false,
    fixed: 'left',
  },
  {
    label: '业务申请编号',
    prop: 'appNo',
    'show-overflow-tooltip': true,
    'min-width': '160px',
    fixed: 'left',
  },
  {
    label: '凭证编号',
    prop: 'voucherNo',
    'show-overflow-tooltip': true,
    'min-width': '140px',
  },
  {
    label: '业务类型',
    prop: 'assetBusiType',
    'show-overflow-tooltip': true,
    'min-width': '120px',
    isFormatDict: true,
  },
  {
    label: '买方企业名称',
    prop: 'buyerCompanyName',
    'show-overflow-tooltip': true,
    'min-width': '120px',
  },
  {
    label: '卖方企业名称',
    prop: 'custCompanyName',
    'show-overflow-tooltip': true,
    'min-width': '140px',
  },
  {
    label: '占用额度类型',
    prop: 'busiType',
    'show-overflow-tooltip': true,
    'min-width': '160px',
    isFormatDict: true,
  },
  {
    label: '融资申请金额（元）',
    prop: 'amount',
    'show-overflow-tooltip': true,
    'min-width': '160px',
    isFormatMoney: true,
    align: 'right',
  },
  {
    label: '实际放款金额（元）',
    prop: 'useAmount',
    'show-overflow-tooltip': true,
    'min-width': '160px',
    isFormatMoney: true,
    align: 'right',
  },
  {
    label: '融资到期日',
    prop: 'expireDate',
    'show-overflow-tooltip': true,
    'min-width': '140px',
  },
  {
    label: '额度占用期限（天）',
    prop: 'period',
    'show-overflow-tooltip': true,
    'min-width': '160px',
  },
];
